network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses: [{{ ansible_eth0.ipv4.address }}/24]
      routes:
      - to: default
        via: 192.168.200.1
      nameservers:
        addresses: 
          - 192.168.200.3
          - 192.168.1.40
          - 192.168.1.41
        search: 
          - cons.tsk.ru

