---
- name: netplan config create
  ansible.builtin.template:
    src: config.yaml
    dest: /etc/netplan/config.yaml
    owner: root
    group: root
    mode: '0644'
  notify: netplan config apply


# configure uwf rules

- name: Default outgoing
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Default incoming
  community.general.ufw:
    default: deny
    direction: incoming

- name: Allow access to OpenSSH
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Allow all access to tcp port 80 443
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - '80'
    - '443'

- name: start and enable service
  community.general.ufw:
    state: enabled

- name: Set logging
  ufw:
    logging: 'on'
